apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inception-retrained-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: inception-retrained-server
    spec:
      containers:
      - name: inception-retrained-container
        image: nbortolotti/serving_inception3_poets
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: inception-retrained-service
  name: inception-retrained-service
spec:
  ports:
  - port: 8501
    targetPort: 8501
  selector:
    app: inception-retrained-server
  type: LoadBalancer